import { ADMIN_PATHS, COMPANY_DASHBOARD_PATHS, CUSTOMER_PATHS } from "./paths";

// Role definitions
export const USER_ROLES = {
  OWNER: "owner",
  ADMIN: "admin",
  AGENT: "agent",
  CUSTOMER: "customer",
  MANAGER: "manager",
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

// Permission definitions
export const PERMISSIONS = {
  // Property permissions
  CREATE_PROPERTY: "create:property",
  EDIT_PROPERTY: "edit:property",
  DELETE_PROPERTY: "delete:property",
  PUBLISH_PROPERTY: "publish:property",
  FEATURE_PROPERTY: "feature:property",
  APPROVE_PROPERTY: "approve:property",

  // Agent management
  CREATE_USER: "create:user",
  EDIT_USER: "edit:user",
  DELETE_USER: "delete:user",

  // Company management
  EDIT_COMPANY: "edit:company",
  ACCESS_COMPANY_DASHBOARD: "access:company:dashboard",

  // Favorites and saved searches (customer)
  MANAGE_SAVED_PROPERTIES: "manage:saved:properties",
  MANAGE_SAVED_SEARCHES: "manage:saved:searches",
  MANAGE_MY_PROFILE: "manage:menu:myPorfile",

  // Sidebar menu access
  ACCESS_PROPERTIES: "access:menu:properties",

  ACCESS_MANAGEMENT: "access:menu:management",
  ACCESS_POINTS: "access:menu:points",
  ACCESS_SUBSCRIPTION: "access:menu:subscription",
  ACCESS_TOPUP: "access:menu:topup",
  ACCESS_SETTINGS: "access:menu:settings",

  // Admin
  ADMIN_DASHBOARD: "admin:dashboard",
  CUSTOMERS_DATA: "admin:customersData",
  COMPANIES_DATA: "admin:companiesData",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Role-based permission mappings
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [USER_ROLES.OWNER]: [
    // Full system access

    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.DELETE_PROPERTY,
    PERMISSIONS.PUBLISH_PROPERTY,
    PERMISSIONS.FEATURE_PROPERTY,
    PERMISSIONS.APPROVE_PROPERTY,

    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,

    PERMISSIONS.EDIT_COMPANY,
    // PERMISSIONS.ACCESS_CUSTOMER_DASHBOARD,
    PERMISSIONS.ACCESS_COMPANY_DASHBOARD,

    // PERMISSIONS.MANAGE_SAVED_PROPERTIES,
    // PERMISSIONS.MANAGE_SAVED_SEARCHES,
    PERMISSIONS.ACCESS_PROPERTIES,
    PERMISSIONS.ACCESS_MANAGEMENT,
    PERMISSIONS.ACCESS_POINTS,
    PERMISSIONS.ACCESS_SUBSCRIPTION,
    PERMISSIONS.ACCESS_TOPUP,
    PERMISSIONS.ACCESS_SETTINGS,
  ],

  [USER_ROLES.ADMIN]: [
    // Administrative access

    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.DELETE_PROPERTY,
    PERMISSIONS.PUBLISH_PROPERTY,
    PERMISSIONS.FEATURE_PROPERTY,
    PERMISSIONS.APPROVE_PROPERTY,

    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    // PERMISSIONS.ACCESS_COMPANY_DASHBOARD,

    PERMISSIONS.ADMIN_DASHBOARD,
    PERMISSIONS.CUSTOMERS_DATA,
    PERMISSIONS.COMPANIES_DATA,
  ],

  [USER_ROLES.AGENT]: [
    // Property management

    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.ACCESS_COMPANY_DASHBOARD,
    PERMISSIONS.ACCESS_PROPERTIES,
    PERMISSIONS.ACCESS_SETTINGS,
  ],

  [USER_ROLES.MANAGER]: [
    // Administrative access

    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.DELETE_PROPERTY,
    PERMISSIONS.PUBLISH_PROPERTY,
    PERMISSIONS.FEATURE_PROPERTY,
    PERMISSIONS.APPROVE_PROPERTY,

    PERMISSIONS.ACCESS_COMPANY_DASHBOARD,

    PERMISSIONS.ACCESS_PROPERTIES,
    PERMISSIONS.ACCESS_MANAGEMENT,
    // PERMISSIONS.ACCESS_WALLET_MENU,
    // PERMISSIONS.ACCESS_SUBSCRIPTION_MENU,
    // PERMISSIONS.ACCESS_TOPUP_MENU,
    PERMISSIONS.ACCESS_SETTINGS,
  ],
  [USER_ROLES.CUSTOMER]: [
    PERMISSIONS.MANAGE_MY_PROFILE,
    PERMISSIONS.MANAGE_SAVED_PROPERTIES,
    PERMISSIONS.MANAGE_SAVED_SEARCHES,
  ],
};

// Route permission mappings - which permissions are required for specific routes
export const ROUTE_PERMISSIONS: Record<string, Permission[]> = {
  // Dashboard routes
  "/company/dashboard": [PERMISSIONS.ACCESS_COMPANY_DASHBOARD],

  // Property routes
  "/properties/create": [PERMISSIONS.CREATE_PROPERTY],
  "/properties/edit": [PERMISSIONS.EDIT_PROPERTY],
  "/properties/delete": [PERMISSIONS.DELETE_PROPERTY],


  // Company 
  [COMPANY_DASHBOARD_PATHS.addNewProperty]: [PERMISSIONS.CREATE_PROPERTY],
  [COMPANY_DASHBOARD_PATHS.settings]: [PERMISSIONS.EDIT_COMPANY],
  [COMPANY_DASHBOARD_PATHS.properties]: [PERMISSIONS.ACCESS_PROPERTIES],
  [COMPANY_DASHBOARD_PATHS.accessManagement]: [PERMISSIONS.ACCESS_MANAGEMENT],
  [COMPANY_DASHBOARD_PATHS.points]: [PERMISSIONS.ACCESS_POINTS],
  [COMPANY_DASHBOARD_PATHS.subscriptionPlans]: [PERMISSIONS.ACCESS_SUBSCRIPTION],
  [COMPANY_DASHBOARD_PATHS.topUp]: [PERMISSIONS.ACCESS_TOPUP],
  [COMPANY_DASHBOARD_PATHS.settings]: [PERMISSIONS.ACCESS_SETTINGS],

  // Customer dashboard routes
  [CUSTOMER_PATHS.savedSearches]: [PERMISSIONS.MANAGE_SAVED_SEARCHES],
  [CUSTOMER_PATHS.savedProperties]: [PERMISSIONS.MANAGE_SAVED_PROPERTIES],
  [CUSTOMER_PATHS.myProfile]: [PERMISSIONS.MANAGE_MY_PROFILE],

  // manageuper Admin Routes
  [ADMIN_PATHS.dashboard]: [PERMISSIONS.ADMIN_DASHBOARD],
  [ADMIN_PATHS.customersData]: [PERMISSIONS.CUSTOMERS_DATA],
  [ADMIN_PATHS.companiesData]: [PERMISSIONS.COMPANIES_DATA],
};
